const quotes = [
    {quote: "The bad news is time flies. The good news is you’re the pilot.", from: "Michael Altshuler"},
    {quote: "Life has got all those twists and turns. You’ve got to hold on tight and off you go.", from: "Nicole Kidman"},
    {quote: "You are never too old to set another goal or to dream a new dream.", from: "Malala Yousafzai"},
    {quote: "Never regret anything that made you smile.", from: "Mark Twain"},
    {quote: "The best way to predict your future is to create it.", from: "Abraham Lincoln"},
    {quote: "The best time to plant a tree was 20 years ago. The second best time is now.", from: "African proverb"},
    {quote: "It’s not what happens to you, but how you react to it that matters.", from: "Epictetus"},
    {quote: "Stay hungry, stay foolish", from: "Steven Paul Jobs, co-founder and CEO of Apple, business magnate"},
    {quote: "If I would have asked people what they wanted, they would have said faster horses.", from: "Henry Ford, American industrialist, founder of the Ford Motor Company"},
    {quote: "Whatever you do, always give 100%. Unless you’re donating blood.", from: "Bill Murray"},
    {quote: "The secret of getting ahead is getting started.", from: "Mark Twain"},
    {quote: "Waking up this morning, I smile. 24 brand new hours are before me. I vow to live fully in each moment.", from: "Thich Nhat Hanh"},
    {quote: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", from: "Maya Angelou"},
    {quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", from: "Mother Teresa"},
    {quote: "Don’t judge each day by the harvest you reap but by the seeds that you plant.", from: "Robert Louis Stevenson"},
    {quote: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", from: "Martin Luther King Jr."},
    {quote: "Today is your Opportunity to build the tomorrow you want", from: "Ken Poirot"},
    {quote: "Ambition is the path to success. Persistence is the vehicle you arrive in.", from: "Bill Bradley"},
    {quote: "Rice is great if you’re really hungry and want to eat two thousand of something.", from: "Mitch Hedberg"},
    {quote: "My fake plants died because I did not pretend to water them.", from: "Mitch Hedberg"},
    {quote: "I’m sick of following my dreams. I’m just going to ask them where they’re goin’, and hook up with them later.", from: "Mitch Hedberg"},
    {quote: "I like vending machines because snacks are better when they fall. If I buy a candy bar at the store, oftentimes I will drop it so that it achieves its maximum flavor potential.", from: "Mitch Hedberg"},
    {quote: "An escalator can never break: It can only become stairs. You should never see an ‘Escalator Temporarily Out Of Order’ sign, just ‘Escalator Temporarily Stairs. Sorry for the convenience.'", from: "Mitch Hedberg"},
    {quote: "I haven’t slept for ten days, because that would be too long.", from: "Mitch Hedberg"},
    {quote: "The beautiful thing about learning is that no one can take it away from you.", from: "B.B. King"},
    {quote: "Follow your passion. It will lead you to your purpose.", from: "Oprah Winfrey"},
    {quote: "The undertaking of a new action brings new strength.", from: "Richard L. Evans"},
    {quote: "I don’t like to gamble, but if there’s one thing I’m willing to bet on, it’s myself.", from: "Beyoncé"},
    {quote: "Everyone you admire was once a beginner.", from: "Jack Butcher"},
    {quote: "The ones who are crazy enough to think they can change the world, are the ones that do.", from: "Steven Paul Jobs, co-founder and CEO of Apple, business magnate"},
    {quote: "All progress takes place outside the comfort zone.", from: "Michael John Bobak"},
    {quote: "You must expect great things of yourself before you can do them.", from: "Michael Jordan"},
    {quote: "Don’t ask if your dream is crazy, ask if it’s crazy enough.", from: "Lena Waithe"},
    {quote: "Being your true self is the most effective formula for success there is.", from: "Danielle LaPorte"},
    {quote: "拜託不要有 bug ", from: "Michael Chuang"},
    
]

export default quotes;